// The renderer build (PRD 6.1: Vite 8.3.1, PRD 6.2: dashboard via Vite).
//
// One build, three pages, one artefact (LD-FR-10, NT-FR-12):
//
//   - `src/dashboard/index.html` is the live dashboard and the page the hub serves
//     at `/`, so it has to be the built `index.html`.
//   - `src/dashboard/prototype/index.html` is the approved static design prototype.
//     DP-4 approved it as a design artefact and the layout the live page draws with
//     is its layout, so it stays in the same build rather than being deleted or
//     pushed behind a second config.
//   - `src/dashboard/card.html` is the notification surface's card document. The
//     window agent-ping creates loads it over the hub's own loopback origin at
//     exactly the path SURFACE_DOCUMENT_PATH names (`/card.html`,
//     src/notify/surface/electron-host.ts), so the build has to emit
//     `card.html` at the root of the output for that request to stop being a 404.
//     It is an entry beside the other two rather than a page generated by a script,
//     so the card's own view is compiled from the same TypeScript source the Electron
//     main process compiles and no copy step exists (NT-FR-02).
//
// `base` is relative because the same artefact has to render identically in the
// Electron application window and from the loopback origin; an absolute base would
// only work for one of them, and a window-specific code path is a defect. The card
// document is no exception: it is loaded from the loopback origin, but a relative
// href is what keeps one artefact correct wherever it is served from.
//
// `outDir` sits outside `root`, so `emptyOutDir` is stated explicitly: Vite refuses
// to clear a directory it does not own unless it is told to, and a stale hashed
// asset left behind from the previous build is a page that serves two scripts.
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'

const dashboardRoot = fileURLToPath(new URL('./src/dashboard', import.meta.url))

export default defineConfig({
  root: dashboardRoot,
  base: './',
  resolve: {
    // Mirrors the `@/*` path map in tsconfig.json, because Vite does not read
    // tsconfig paths. Node-hosted code under src/ uses relative imports instead.
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  build: {
    outDir: fileURLToPath(new URL('./dist/dashboard', import.meta.url)),
    emptyOutDir: true,
    target: 'es2022',
    sourcemap: true,
    // No modulepreload polyfill, stated rather than inherited.
    //
    // It is Vite's default, and its presence is invisible in the output: whether the
    // empty polyfill module survives tree-shaking as a shared chunk depends on how
    // many entries the build has, so adding a third page silently appended a
    // `<link rel="modulepreload">` to the two pages that already shipped without one.
    // A page that changes because an unrelated entry was added is a page nobody
    // reviewed, and the two existing pages are the reference this product is held to.
    //
    // The polyfill only helps browsers that do not implement `rel="modulepreload"` at
    // all (Safari before 17). Dropping it costs a preloading hint on those browsers
    // and nothing else: no page here depends on a preload link to execute, and the
    // surface's own window is Chromium, where modulepreload is long since native.
    modulePreload: { polyfill: false },
    rollupOptions: {
      input: {
        // The live page. Named `index` so it is the built `index.html` the hub's
        // static route maps `/` onto.
        index: resolve(dashboardRoot, 'index.html'),
        // The approved prototype, kept as a second page in the same artefact.
        prototype: resolve(dashboardRoot, 'prototype/index.html'),
        // The card document. Named `card` so the build emits `card.html` at the
        // output root, which is the path the surface window requests. A third entry
        // in this list is the whole of "served"; no route, no origin and no
        // content-security policy of its own exist for it (NT-FR-03, NT-FR-12).
        card: resolve(dashboardRoot, 'card.html'),
      },
    },
  },
})
