-- agent-ping durable schema (EL-FR-02, ADR-003, APX-FR-01).
--
-- PRIVACY BOUNDARY
-- This file is the whole privacy mechanism, and it is a mechanism rather than
-- a promise: the exact column set of every table below is written out
-- literally in tests/storage/schema.test.ts, so adding a content-bearing
-- column fails that test until a human adds it to the expected list and
-- accepts in writing that it cannot hold content. Nothing in this schema may
-- hold a prompt, a model response, tool output, file contents, a diff or a
-- transcript, and there is no column for "what was said in a turn". The log
-- records that something happened, never what was said.
--
-- The persisted set, and nothing beyond it (APX-FR-01, ADR-003):
--   harness, repository short name and full path, session identifier, event
--   class and optional subtype, raw event type, dedupe key, occurrence and
--   receipt timestamps, acknowledgement and resolution state.
--
-- IDENTITY
-- The repository short name (the session's directory basename) is the identity
-- the product groups and labels by (APX-CON-09, ADR-008). The full path
-- travels alongside it for hover detail and is never a key: no index, no
-- primary key and no uniqueness constraint is declared on repo_full_path, and
-- tests/storage/schema.test.ts fails if one ever is.
--
-- MIGRATION DISCIPLINE
-- Migrations are forward-only, numbered from 1 with no gaps, and applied
-- idempotently on every open by src/storage/db.ts. Never edit a migration that
-- has shipped: append a new `-- migration: N` block instead. Every column must
-- be reachable from a migration, because an unreadable database is deleted and
-- recreated from these statements (EL-FR-11, APX-CON-03), and a column that
-- only a debug path created would vanish on the rebuild while the
-- exact-column-set assertion kept it in the expected list.
--
-- The tables are STRICT, so a column can only ever hold a value of its declared
-- type. That is not a privacy feature on its own, but it means a text column
-- cannot quietly become a BLOB holding a serialised payload.

-- migration: 1 initial content-free durable log
--
-- One row per harness session, keyed by the harness's own session identifier.
-- The repository short name is the identity the dashboard groups by; the full
-- path is carried for hover detail and is deliberately not part of any key.
--
-- `work_signal` is the turn's work flag: 1 when the turn that produced the
-- session's last event had recorded a tool call, a file edit or a todo update,
-- 0 when it had not. It is a flag and never a count, because a per-turn tally
-- of what the agent did is a transcript wearing a numeric disguise
-- (EL-FR-05). The domain classifier owns the decision (src/domain/classify.ts,
-- EL-3); the store only records the value that decision produced.
--
-- `state` is the observed session lifecycle from PRD 10, restricted to the
-- vocabulary that document defines. insertEvent derives three of these from
-- the class of the event it just stored: needs-you -> blocked, finished ->
-- finished, fyi -> running. The remainder are the initial default and the two
-- states a later contract change records; the constraint is closed now so a
-- value outside PRD 10 can never reach the dashboard.
CREATE TABLE sessions (
  session_id      TEXT    NOT NULL PRIMARY KEY,
  harness         TEXT    NOT NULL,
  repo_short_name TEXT    NOT NULL,
  repo_full_path  TEXT    NOT NULL,
  first_seen_at   TEXT    NOT NULL,
  last_seen_at    TEXT    NOT NULL,
  state           TEXT    NOT NULL DEFAULT 'unknown'
                 CHECK (state IN ('unknown', 'running', 'blocked', 'finished', 'idle-after-nothing', 'gone')),
  work_signal     INTEGER NOT NULL DEFAULT 0 CHECK (work_signal IN (0, 1))
) STRICT, WITHOUT ROWID;

-- One row per classified event. The event identifier is generated by the store
-- at insert time, because the normalized envelope carries identity and class
-- rather than a row key, and it is what the single ack route addresses.
--
-- `class` and `subtype` are the three loudness classes and the five fyi
-- subtypes of ADR-004, enforced by the database and not only by TypeScript: a
-- new adapter cannot invent a class and store it. An fyi event may omit its
-- subtype, but no other class may carry one.
--
-- Timestamps are ISO 8601 UTC text, so lexicographic order is chronological
-- order and a range query needs no conversion function. Their format is
-- validated where untrusted input enters (the ingest route, HC-3), not here.
--
-- `ack_state` and `resolution_state` are two independent facts, not one:
-- "resolved by the harness" and "acknowledged by the developer" are recorded
-- separately so history can show which one happened (PRD 10, and the feature
-- document's Open Questions 2). Neither is ever cleared by anything else
-- (EL-FR-08). The two states are what this records; a timestamp for each is a
-- later contract change, because nothing in v1 renders one (LD-FR-08 lists
-- class, repository, session, timestamp and state).
CREATE TABLE events (
  event_id         TEXT    NOT NULL PRIMARY KEY,
  session_id       TEXT    NOT NULL REFERENCES sessions (session_id),
  class            TEXT    NOT NULL CHECK (class IN ('needs-you', 'finished', 'fyi')),
  subtype          TEXT    CHECK (subtype IS NULL OR subtype IN ('error', 'retry', 'long-tool-call', 'compaction', 'token-burn')),
  raw_event_type   TEXT    NOT NULL,
  occurred_at      TEXT    NOT NULL,
  received_at      TEXT    NOT NULL,
  dedupe_key       TEXT    NOT NULL,
  ack_state        TEXT    NOT NULL DEFAULT 'unacknowledged'
                   CHECK (ack_state IN ('unacknowledged', 'acknowledged')),
  resolution_state TEXT    NOT NULL DEFAULT 'unresolved'
                   CHECK (resolution_state IN ('unresolved', 'resolved')),
  CHECK (subtype IS NULL OR class = 'fyi')
) STRICT, WITHOUT ROWID;

-- Local counters only: a name, a non-negative count and when it last moved
-- (EL-FR-10, PRD 11). A counter is a number, so this table cannot carry
-- content even in principle, and the read path is a single accessor rather
-- than a query surface.
CREATE TABLE counters (
  name       TEXT    NOT NULL PRIMARY KEY,
  value      INTEGER NOT NULL DEFAULT 0 CHECK (value >= 0),
  updated_at TEXT    NOT NULL
) STRICT, WITHOUT ROWID;

-- The migration record (EL-FR-02). One row per applied migration, so the
-- version the store is running is stored in the database rather than only in
-- the build.
--
-- This table is created by src/storage/db.ts, not by a migration block below,
-- because the runner has to read it to know which migrations are pending. It is
-- the one table in the schema that no `-- migration:` block creates, it is
-- written only by the runner, and its column set is asserted exactly like every
-- other table's. It must never gain a third column: there is no migration to
-- carry it, so a rebuild would drop it.

-- Session plus occurrence time: the history and per-session reads, which are
-- the queries the dashboard history panel and the event detail route run.
CREATE INDEX idx_events_session_occurred ON events (session_id, occurred_at);

-- Class plus acknowledgement state: the pending set, which is the tray badge's
-- single source of truth (NT-FR-05) and is read on every dashboard poll.
CREATE INDEX idx_events_class_ack ON events (class, ack_state);

-- One event per dedupe key. The dedupe key is derived from identity alone
-- (harness, session, block or transition identifier), so this constraint is what
-- makes a repeated permission ask and a polled duplicate the same event rather
-- than two (EL-FR-07), and what makes push and poll safe to run at once.
CREATE UNIQUE INDEX ux_events_dedupe_key ON events (dedupe_key);

-- Repository grouping. The dashboard's question is which project is asking, so
-- the short name is the grouping key (APX-CON-09, ADR-008). There is
-- deliberately no index on repo_full_path: the full path is never a key.
CREATE INDEX idx_sessions_repo_short_name ON sessions (repo_short_name);
