// The security boundary, as decisions: who may be answered at all, and who may
// write (HC-FR-06, APX-CON-01, APX-CON-08, PRD 8, ADR-002).
//
// FOUR LAYERS, AND WHY IT IS FOUR
// An unauthenticated port on loopback looks harmless and is not: a proxy, a
// container port mapping, a forwarded socket, or a page the developer visits can
// all turn it into a channel. Each layer closes a different one of those, and each
// fails silently on its own, so each is here as a named, testable thing rather
// than as a habit:
//
//   1. The bind. `127.0.0.1`, never a wildcard. That is src/hub/server.ts, which
//      is where the socket is created.
//   2. The address. `isLoopbackAddress` below, applied to the request's socket
//      before routing, so a refused peer reaches no handler at all. Binding alone
//      is not enough: what the check must read is the socket, never a
//      caller-supplied `x-forwarded-for`, which is a claim rather than an address.
//   3. The token. One random value per install, in an owner-only file, required on
//      the write route - the one route that changes an existing record - and on
//      nothing else.
//   4. The headers. A strict content-security-policy with the dashboard, and no
//      cross-origin header of any kind, because the daemon is unauthenticated on
//      read and a permissive one hands any page on the machine a channel to it.
//
// WHY THE TOKEN IS A SEPARATE FILE, NOT A FIELD IN THE RUNTIME FILE
// The runtime file is a pointer *and* a lock, read by adapters, and it is
// `0o600` already - so the token could live there. It does not, for two reasons.
// A pointer is read by anything that can see the state directory, and the token
// is the difference between "may read session metadata" and "may change it";
// keeping them in one file means any future reader of the pointer holds the write
// capability. And a lock file gets deleted, rewritten and reclaimed on every
// restart, whereas the token has to survive those untouched: regenerated by
// reinstall, and by nothing else (PRD 16 Open Question 9). The state directory is
// where both live, so the runtime file's `stateDir` field is still the one lookup a
// client needs (src/hub/runtime-file.ts).
//
// WHY THE TOKEN GUARDS ONE ROUTE AND NOT THE SERVER
// Appending an event (`POST /api/ingest`) is not a control surface: it creates a
// row and changes nothing that already exists, it reaches no session, no agent and
// no harness, and requiring a secret there would mean every harness adapter had to
// hold the write capability to report what it observed (ADR-002, APX-CON-08). The
// route that can change an existing record is the one that needs the token, and
// the check lives *in that route* rather than in a shared middleware that has to
// be correct about which routes to guard: there is exactly one such route, and the
// registry already refuses to register a second one that claims it
// (src/hub/server.ts).
//
// WHAT THIS MODULE DOES NOT DO
// It does not authenticate the local user. On a single-user machine anything
// running as that user can reach the loopback port; the boundary exists so the
// daemon cannot become a *remote* control and so unauthenticated reads are not
// usable cross-origin, which is a different claim from access control and is
// never described as one.
//
// The token is never written to a log line, an error body, a URL or a served
// asset: every refusal sentence in src/hub/routes/ack.ts is a literal in that
// file, and tests/hub/security.test.ts asserts the token appears in no response
// body, no header and no served byte.
//
// This module opens no socket, spawns nothing and calls nothing off the machine
// (APX-CON-12). It reads and writes one file inside the state directory.

import { randomBytes as nodeRandomBytes, timingSafeEqual } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import {
  OWNER_ONLY_FILE_MODE,
  ensureOwnerOnlyFile,
  ensureStateDir,
  resolveStateDir,
} from '../storage/paths.js'

// ---------------------------------------------------------------------------
// Layer 2: the address check
// ---------------------------------------------------------------------------

/**
 * Is this remote address on the loopback interface?
 *
 * A pure predicate, and the reason the boundary survives a proxy. The address is
 * compared as a value rather than as a string, because one loopback address has
 * several string forms: Node reports an IPv4 client on a dual-stack socket as
 * `::ffff:127.0.0.1`, and refusing that would break the product on a default
 * macOS or Linux configuration.
 *
 * The empty address is not loopback. It appears when a socket has no peer, and a
 * request with no peer is not a request from this machine's user.
 *
 * `::` and `0.0.0.0` are not loopback either: they are the unspecified address, so
 * accepting them would be accepting a claim rather than an address. Nor is
 * `127.0.0.1.evil.example`, which is a name rather than an address: the dotted
 * quad is matched as four bounded decimal parts and nothing may follow them.
 */
export function isLoopbackAddress(remoteAddress: string | undefined | null): boolean {
  if (typeof remoteAddress !== 'string' || remoteAddress.trim() === '') return false
  const address = remoteAddress.trim().toLowerCase()
  if (address === '::1' || address === '0:0:0:0:0:0:0:1') return true
  // An IPv4-mapped IPv6 address is the same host as the address it maps.
  const mapped = address.startsWith('::ffff:') ? address.slice('::ffff:'.length) : address
  if (mapped.includes(':')) return false
  return /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(mapped) && isDottedQuad(mapped)
}

function isDottedQuad(value: string): boolean {
  return value
    .split('.')
    .every(
      (part) => /^\d{1,3}$/.test(part) && Number(part) >= 0 && Number(part) <= 255,
    )
}

// ---------------------------------------------------------------------------
// Layer 4: the response headers
// ---------------------------------------------------------------------------

/**
 * The content-security-policy sent with the dashboard.
 *
 * One named constant so the server and the test that asserts it cannot disagree
 * about what is sent. No `unsafe-inline` and no `unsafe-eval`: when the PixiJS
 * bundle conflicts with one of these directives the fix is to narrow the policy or
 * change the mechanism, never to weaken it (feature document Open Questions 4,
 * and the rule that a weakened policy looks exactly like a working one in review).
 */
export const DASHBOARD_CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self'",
  // PixiJS draws into a canvas and may hand an image back as a data URI.
  "img-src 'self' data: blob:",
  // The live state stream arrives as an EventSource from this same origin.
  "connect-src 'self'",
  "font-src 'self'",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  // A framed dashboard is a confused deputy: the hub is a local daemon and no
  // page on the machine has business framing it.
  "frame-ancestors 'none'",
  "form-action 'none'",
].join('; ')

/**
 * Every cross-origin response header this product must never send.
 *
 * Listed rather than described, because the whole rule is an absence and an
 * absence is invisible in review: a `Access-Control-Allow-Origin: *` added by a
 * merge or a copy-paste looks like any other header. The names are lower-case
 * because HTTP header names are case-insensitive and Node reports them that way.
 */
export const CROSS_ORIGIN_HEADERS = [
  'access-control-allow-origin',
  'access-control-allow-credentials',
  'access-control-allow-methods',
  'access-control-allow-headers',
  'access-control-expose-headers',
  'access-control-max-age',
] as const

/** A header table, as Node reports one. Structural, so both halves can use it. */
export type HeaderBag = Readonly<Record<string, string | string[] | undefined>>

/**
 * Which cross-origin headers are present in this response, whatever their value.
 *
 * Not "which are permissive": none of them may be sent at all. A credentialed
 * `Access-Control-Allow-Origin: *` is illegal in a browser and a
 * `Access-Control-Allow-Origin: http://127.0.0.1:43117` is a hole in every other
 * page, so the only safe answer for this list is the empty one. A pure function of
 * the table, so a test can ask it about every route's real response.
 */
export function crossOriginHeadersPresent(headers: HeaderBag): string[] {
  const present: string[] = []
  for (const name of CROSS_ORIGIN_HEADERS) {
    const value = lookupHeader(headers, name)
    if (value === undefined) continue
    present.push(name)
  }
  return present
}

// ---------------------------------------------------------------------------
// Layer 3: the per-install write token
// ---------------------------------------------------------------------------

/**
 * The token's file inside the state directory.
 *
 * Named for what it is. It sits beside the database and the runtime file, inside
 * the `0o700` directory, and is itself `0o600` - a world-readable token is not a
 * token. The runtime file's `stateDir` field is how a client finds it, which is why
 * that field exists at all.
 */
export const WRITE_TOKEN_FILE_NAME = 'hub-write-token'

/**
 * The header a write carries the token in.
 *
 * A named custom header, and never a query parameter: a query string lands in
 * access logs, in browser history for every dashboard request, and in any copied
 * URL. One header, one spelling, lower-case because that is how HTTP reports it.
 */
export const WRITE_TOKEN_HEADER = 'x-agent-ping-token'

/**
 * How much randomness the token carries.
 *
 * Thirty-two bytes of `randomBytes`, hex-encoded, because a token compared with
 * `timingSafeEqual` must be a fixed width for the comparison to be well defined,
 * and because a 64-character hex string is something an operator can transcribe
 * from a file without a decoding step. It is not a password: there is nobody to
 * brute-force it, and the boundary it guards is "this is not a remote control".
 */
export const WRITE_TOKEN_BYTES = 32

/** What a well-formed token looks like, and what anything else is refused as. */
const WRITE_TOKEN_PATTERN = new RegExp(`^[0-9a-f]{${WRITE_TOKEN_BYTES * 2}}$`)

/** A token file this build cannot use. */
export class WriteTokenError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options)
    this.name = 'WriteTokenError'
  }
}

/** The token an install is using, and where it came from. */
export interface WriteToken {
  /** The value a write must present. Never serialised into any response. */
  readonly token: string
  readonly filePath: string
  /** True when this call created the file, false when it read the existing one. */
  readonly created: boolean
}

/** The token file for a state directory. */
export function writeTokenFilePath(stateDir: string = resolveStateDir()): string {
  return path.join(stateDir, WRITE_TOKEN_FILE_NAME)
}

export interface EnsureWriteTokenOptions {
  /** Defaults to the resolved state directory, honouring AGENT_PING_STATE_DIR. */
  readonly stateDir?: string
  /** Injectable for a test that needs a token it knows the value of. */
  readonly random?: (bytes: number) => Buffer
}

/**
 * The install's write token, creating the file if this is the first start.
 *
 * Read-or-create and never rotate: a regenerated token would silently invalidate
 * the dashboard or the CLI that already holds the old one, and a product that
 * invalidates its own capability without saying so is the kind of fault that
 * surfaces as "the ack button stopped working" a week later. Rotation is a
 * deliberate act - remove the file, restart the hub - and reinstall is the
 * documented reset (PRD 16 Open Question 9).
 *
 * The create is exclusive (`wx`) at `0o600` in a single step, so a token is never briefly
 * empty and never briefly world-readable, and a file that already exists is read instead
 * of rewritten.
 *
 * A file that exists and cannot be understood is a `WriteTokenError` rather than a
 * silent regeneration, for the reason above: a machine with a damaged token file
 * has to be told, not quietly handed a capability that nothing else holds.
 */
export function ensureWriteToken(options: EnsureWriteTokenOptions = {}): WriteToken {
  const stateDir = ensureStateDir(options.stateDir ?? resolveStateDir())
  const target = writeTokenFilePath(stateDir)
  const random = options.random ?? nodeRandomBytes

  if (existsSync(target)) {
    return { token: readWriteToken(stateDir) ?? unusableToken(target), filePath: target, created: false }
  }

  const token = random(WRITE_TOKEN_BYTES).toString('hex')
  if (!WRITE_TOKEN_PATTERN.test(token)) {
    // The only way to reach this is an injected random source that returned the
    // wrong number of bytes, which in production would be a broken entropy source.
    // It is caught here rather than on the first write, because a hub that started
    // and then refused every write would look like a working hub with a broken
    // dashboard.
    throw new WriteTokenError(
      `the random source produced a value that is not a token this build can issue (expected ` +
        `${WRITE_TOKEN_BYTES * 2} hexadecimal characters). Refusing to start rather than serving a ` +
        'write route nobody could ever satisfy (HC-FR-06).',
    )
  }
  try {
    // `wx` plus the mode together: the file is created owner-only or not at all, and a
    // moment of world-readable token is the one thing this file must never have. The
    // umask can only remove bits from a mode, never add them, so 0o600 stays 0o600.
    // The file is *not* pre-created with `ensureOwnerOnlyFile` first: that helper
    // creates an empty file, and an exclusive create against a file this call made is
    // a self-inflicted EEXIST against an empty token.
    writeFileSync(target, `${token}\n`, { mode: OWNER_ONLY_FILE_MODE, flag: 'wx' })
  } catch (cause) {
    if (isAlreadyExists(cause)) {
      // Lost the race against another starter. Its value is the install's value,
      // and reading it is the only correct answer.
      const existing = readWriteToken(stateDir)
      if (existing !== null) return { token: existing, filePath: target, created: false }
    }
    throw new WriteTokenError(
      `the hub write token could not be created at ${target}. The ack route requires this token, so ` +
        'a hub that cannot create it has a control surface nobody can reach - which is reported ' +
        'rather than served with writes refused (HC-FR-06).',
      { cause },
    )
  }
  // Belt and braces: an existing file is tightened rather than trusted, exactly as the
  // runtime file's own create does. A no-op for a file this call just created at 0600.
  ensureOwnerOnlyFile(target)
  return { token, filePath: target, created: true }
}

/**
 * The install's write token, or null when there is no token file.
 *
 * Throws `WriteTokenError` for a file that is present and unusable. A missing file
 * and a damaged file are different situations: the first is a machine that has
 * never installed this build, the second is a machine whose state directory
 * something has interfered with, and only one of them is fixed by starting the hub.
 */
export function readWriteToken(stateDir: string = resolveStateDir()): string | null {
  const target = writeTokenFilePath(stateDir)
  if (!existsSync(target)) return null
  let raw: string
  try {
    raw = readFileSync(target, 'utf8')
  } catch (cause) {
    throw new WriteTokenError(
      `the hub write token at ${target} exists but could not be read. A write whose token cannot ` +
        'be checked is refused, so this is reported rather than treated as absent (HC-FR-06).',
      { cause },
    )
  }
  // Trimmed rather than parsed: the file is one line, and a trailing newline is a
  // convention of every file in the state directory rather than part of the secret.
  const token = raw.trim()
  if (!WRITE_TOKEN_PATTERN.test(token)) {
    throw new WriteTokenError(
      `the hub write token at ${target} is not a token this build issued (expected ` +
        `${WRITE_TOKEN_BYTES * 2} hexadecimal characters). Delete the file and restart the hub to ` +
        'issue a new one; a token that was replaced by something else cannot be honoured silently, ' +
        'because a regenerated token would invalidate every client already holding the old one ' +
        '(HC-FR-06, PRD 16 Open Question 9).',
    )
  }
  return token
}

/** Unreachable: `existsSync` said the file was there a moment ago. */
function unusableToken(target: string): never {
  throw new WriteTokenError(
    `the hub write token at ${target} disappeared between the existence check and the read. ` +
      'Retry the start; another process may be managing the state directory.',
  )
}

// ---------------------------------------------------------------------------
// Presenting a token
// ---------------------------------------------------------------------------

/**
 * What a request carried in the token header.
 *
 * Three cases rather than one, because "no header" and "two headers" are different
 * faults and a client that sends the header twice is not a client whose token can
 * be read: an HTTP/1.1 request with two values for one header is either a
 * confused client or an attempt to have a proxy and the hub disagree about which
 * value is authoritative. Neither is answered with a guess.
 */
export type PresentedWriteToken =
  | { readonly kind: 'absent' }
  | { readonly kind: 'duplicated' }
  | { readonly kind: 'present'; readonly value: string }

/**
 * Read the token header out of a header table.
 *
 * Case-insensitive, because HTTP header names are, and a client that sent
 * `X-Agent-Ping-Token` sent the header this product asks for. A value with
 * surrounding whitespace is trimmed: a header value is not padded in HTTP, and a
 * padded one is a transport artefact rather than a different token.
 */
export function presentedWriteToken(headers: HeaderBag): PresentedWriteToken {
  const raw = lookupHeader(headers, WRITE_TOKEN_HEADER)
  if (raw === undefined) return { kind: 'absent' }
  if (Array.isArray(raw)) {
    const values = raw.filter((value) => value.trim() !== '')
    if (values.length > 1) return { kind: 'duplicated' }
    const only = values[0]
    return only === undefined ? { kind: 'absent' } : { kind: 'present', value: only.trim() }
  }
  if (raw.trim() === '') return { kind: 'absent' }
  return { kind: 'present', value: raw.trim() }
}

/**
 * Do these two values match, without leaking how much of them was right?
 *
 * `timingSafeEqual` over the raw bytes, with the length check folded in: Node's
 * throws on a length mismatch, and the honest way to keep the comparison's cost
 * independent of *how* the guess was wrong is to still run a comparison of the
 * expected length and discard its result. A shorter guess therefore costs the
 * same as a wrong one of the right length, and the answer is a boolean rather than
 * a comparison somebody can time their way into.
 */
export function tokensMatch(expected: string, presented: string): boolean {
  if (expected === '') return false
  const expectedBytes = Buffer.from(expected, 'utf8')
  const presentedBytes = Buffer.from(presented, 'utf8')
  if (presentedBytes.length !== expectedBytes.length) {
    timingSafeEqual(expectedBytes, expectedBytes)
    return false
  }
  return timingSafeEqual(expectedBytes, presentedBytes)
}

/** Why a write was refused at the boundary. Each is answered; none is swallowed. */
export type WriteTokenRefusalCode =
  /** The header was not there at all. */
  | 'token-missing'
  /** The header was there twice. */
  | 'token-duplicated'
  /** The header was there and named the wrong value. */
  | 'token-invalid'

/**
 * The verdict on one write's token.
 *
 * A refusal carries a code and a status and nothing else. It deliberately does not
 * carry the value it compared against, the value it was given, or which of the two
 * was closer: this object is what a route turns into a response body, and a body
 * that can carry a token is a body that can leak one.
 */
export type WriteAuthorisation =
  | { readonly allowed: true }
  | {
      readonly allowed: false
      readonly code: WriteTokenRefusalCode
      /** Always 401. One status for all three, because they are one answer. */
      readonly status: 401
    }

/**
 * The whole of the token check, as a pure function of what a request carried and
 * what the install holds.
 *
 * No socket, no clock, no filesystem, so a test can drive every case - absent,
 * duplicated, wrong, right, and a guess that shares a prefix - without a running
 * hub. That is the point of keeping the extraction, the comparison and the verdict
 * in one place: each is separately testable, and the route that depends on them
 * has nothing left to decide.
 */
export function authoriseWriteToken(input: {
  readonly expected: string
  readonly headers: HeaderBag
}): WriteAuthorisation {
  const presented = presentedWriteToken(input.headers)
  if (presented.kind === 'absent') {
    return { allowed: false, code: 'token-missing', status: 401 }
  }
  if (presented.kind === 'duplicated') {
    return { allowed: false, code: 'token-duplicated', status: 401 }
  }
  if (!tokensMatch(input.expected, presented.value)) {
    return { allowed: false, code: 'token-invalid', status: 401 }
  }
  return { allowed: true }
}

// ---------------------------------------------------------------------------
// What a handler is given
// ---------------------------------------------------------------------------

/**
 * The boundary, as the one object a handler receives it through.
 *
 * Built once by the composition root and reached through `HubServices`, so there is
 * one token per install, one place that compares it, and no route that could hold a
 * second copy. `writeToken` is in-process only: it is on this object because the
 * ack route has to compare against something, and it is not on any read route, in
 * any response, in the served dashboard or in the runtime file.
 */
export interface HubSecurity {
  /** The install's token. Never serialised, never logged, never served. */
  readonly writeToken: string
  readonly writeTokenFilePath: string
  /** The header a write must carry it in. Published so a client need not guess. */
  readonly writeTokenHeader: string
  /** True when this start created the token file rather than reading it. */
  readonly createdWriteToken: boolean
  /**
   * Judge one write's headers against this install's token.
   *
   * The verdict, not the token: a route that could reach the value could also
   * accidentally put it somewhere, so a handler only ever learns whether it may
   * proceed.
   */
  authorise(headers: HeaderBag): WriteAuthorisation
}

/**
 * The options `createHubSecurity` takes.
 *
 * A named alias rather than an empty interface, because a hub's options are a thing a
 * reader looks for and a linter is right that an interface declaring no members says
 * nothing the supertype does not.
 */
export type CreateHubSecurityOptions = EnsureWriteTokenOptions

/**
 * Build the boundary for one install.
 *
 * Deliberately eager: the token file is created or read at start, so a hub that is
 * serving is a hub whose write route can be reached. The alternative - looking for
 * the token on the first write - moves a start-up failure to the moment a developer
 * clicks something, which is the wrong time to learn that the state directory is
 * not writable.
 */
export function createHubSecurity(options: CreateHubSecurityOptions = {}): HubSecurity {
  const issued = ensureWriteToken(options)
  return {
    writeToken: issued.token,
    writeTokenFilePath: issued.filePath,
    writeTokenHeader: WRITE_TOKEN_HEADER,
    createdWriteToken: issued.created,
    authorise: (headers: HeaderBag): WriteAuthorisation =>
      authoriseWriteToken({ expected: issued.token, headers }),
  }
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

/** One header's value, case-insensitively, or undefined when it is not there. */
function lookupHeader(headers: HeaderBag, name: string): string | string[] | undefined {
  const wanted = name.toLowerCase()
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === wanted) return value
  }
  return undefined
}

function isAlreadyExists(cause: unknown): boolean {
  return (
    typeof cause === 'object' &&
    cause !== null &&
    'code' in cause &&
    (cause as { code?: unknown }).code === 'EEXIST'
  )
}
